version: '3'
services:
  arrow-adbc-issue-1283:
    container_name: arrow-adbc-issue-1283
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REPRODUCE_ISSUE=false
    environment:
      - SNOWFLAKE_USERNAME=${SNOWFLAKE_USERNAME}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
    volumes:
      - ${PWD}/data_lakehouse:/app/data_lakehouse